### ISSUE TITLE
Retrieving data from AEM alongside the template as a separate service

### ISSUE THREAD

**Issue by Edhendil** [Knotx/knotx-data-bridge#18]
To retrieve data (configuration, translations) from AEM for it to be available in the context of fragment rendering in Knot.x you have to use one of following appoaches:
* AEM can directly render its data into the template inside knot.x snippet - the easiest way and the messiest one at the same time, we're mixing two different rendering engines in one place (HTL and handlebars), also you can't process this data together with data from services
* render AEM data as JSON in the data-knotx-params attribute - that's fine unless there are multiple handlebars snippets on the page where you have to provide the same parameters in every snippet in order to avoid multiple executions of the same service
* custom knot - it would retrieve data from AEM, cache it and enrich all fragments - but you have to develop a custom knot, add it to the chain and prepare a special resource/servlet on AEM returning required data, additionally it requires another roundtrip in addition to template retrieval
* retrieve data within a service - additional roundtrip, you have to manage the cache yourself

What I would like to achieve is the following scenario:
* define Sling Model which retrieves all required data from JCR
* render that data as JSON within <script type="application/json" data-provides="service-name"> only once on the page
* expose the JSON as a service under the provided name for handlebars snippets to consume - it could be either done through the data-service attribute or programmatically from within another service

Pros:
* no additional roundtrip to AEM
* data is treated as yet another service, the only difference being the response comes together with the template so it is "cached" to start with

Affected elements:
* Data bridge would have to allow calling a service (with cache included) from another service
* Data bridge would have to allow registering new services in the scope of a single request - data could be represented as Single<T> created by Single.just() factory method
* Splitter would have to support the special new <script> element - it might be the case there should be introduced a plugin mechanism of some sorts for splitter so more elements can be processed in a special way

I would like to discuss this idea with you and implement it if approved.

**Comment by Skejven** [comment]
@Edhendil 
this PR might be partially usefull in context of the approaches first and second point [knotx-426](https://github.com/Cognifide/knotx/pull/426). But it should be changed a little to match better your idea, instead of key-value it should store key-json.

I'm not sure if that idea is generic enough to be a part of the data-bridge.
What is the problem of having a service exposed by AEM (as you wrote with Sling Model that retrieves all the JCR data)? Knot.x does not call single service several times in the scope of a single page request.
There is a cache layer built-in in the data-bridge with request grouping.
When a single `data-source` is used among several knotx snippets, only one call to the service is done (assuming data source is called with the same params). Other snippets use cached value.
In the context of AEM that data could be cached on the Dispatcher level, so there would be only one extra request to the AEM itself.

**Comment by marcinczeczko** [comment]
@Edhendil Let me take this one. The problem you describing is actually a configuration used by many Knot.x implementations. What I can suggest to you is to 
- get all address formats exposed by AEM as JSON (e.g. you can configure all formats on some sort of config page, and implement servlet to return  a proper JSON if that page was reguested)
- create a Verticle that retrieves that data from AEM e.g. periodically and caches in memory (assuming there are no gigs of data :))
- in your datasource/adapter that talks to the salesforce, simple get the address formats based on the decision from SF API - keep in mind that you can always talk to other vert.x verticles through the event bus.

This is just idea... and there are more ways how to make it happen - not everything fits as a knot.x core functionality.

**Comment by Skejven** [comment]
@Edhendil 
The idea you described is now fully available with [Fragments Processing](https://github.com/Knotx/knotx-fragments-handler) - you may check it out in the [2.0.0-RC1](https://search.maven.org/search?q=g:io.knotx%20AND%20v:2.0.0-RC1) at the moment. You may define any Action before Template Engine (e.g. read some additional data and put it into context).
Closing the issue.
